1. Read the Data!

In [ ]:
file_path = '/content/drive/MyDrive/makeSenseOfCensus.csv'

Loading the data

In [ ]:
import numpy as np
data = np.genfromtxt(file_path,delimiter=',',skip_header = 1)
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [ ]:
type(data)

numpy.ndarray

In [ ]:
data.shape

(1000, 8)

Step : 2 Append the Data!

In [ ]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]

In [ ]:
new_data = np.concatenate((data,new_record),axis = 0)
new_data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [ ]:
new_data.shape

(1001, 8)

Step 3 : Check if it's a young country or old country

In [ ]:
age = new_data[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

In [ ]:
max_age = age.max()
max_age

90.0

In [ ]:
min_age = age.min()
min_age

17.0

In [ ]:
age_mean = age.mean
age_mean

<function ndarray.mean>

In [ ]:
age_std = age.std
age_std

<function ndarray.std>

Step 4: Let's check the country's race distribution to identify the minorities

In [ ]:
race = new_data[:,2]
race

array([4., 4., 4., ..., 4., 4., 4.])

In [ ]:
race_0 = race[race==0]
race_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
race_1 = race[race==1]
race_2 = race[race==2]
race_3 = race[race==3]
race_4 = race[race==4]

In [ ]:
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)
print(len_0, len_1, len_3, len_4)

10 27 6 848


In [ ]:
len(race_4)

848

In [ ]:
lenOfrace = [len_0,len_1,len_2,len_3,len_4]
np.array(lenOfrace).min()

6

In [ ]:
minority_race = 3
minority_race

3

Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

In [ ]:
senior_citizen = new_data[age>60]
senior_citizen

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

In [ ]:
working_sum_hours = np.sum(senior_citizen[:,6])

In [ ]:
senior_citizen_len = len(senior_citizen)
senior_citizen_len

61

In [ ]:
avg_working_hours = working_sum_hours/ senior_citizen_len
avg_working_hours

31.42622950819672

Step 6: Let's check that higher educated people have better pay in general.
Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.
Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [ ]:
edu = data[:,1]
edu

array([13., 13.,  9.,  7., 13., 14.,  5.,  9., 14., 13., 10., 13., 13.,
       12., 11.,  4.,  9.,  9.,  7., 14., 16.,  9.,  5.,  7.,  9., 13.,
        9., 10.,  9.,  9., 12., 10., 13., 10., 10.,  7., 10.,  9., 10.,
       12.,  5., 13., 13.,  9.,  9., 13.,  9., 14., 11., 11., 10.,  9.,
       15., 13.,  9., 10.,  3., 11.,  9.,  9., 13.,  4.,  9., 16., 10.,
        9., 10.,  9., 10., 10., 10., 13., 13., 10., 10.,  9., 12.,  6.,
        7.,  4.,  9., 13.,  9.,  9.,  9.,  9.,  9., 14.,  5., 16., 11.,
       10., 10.,  9., 13., 10., 16., 10., 12.,  9., 14., 13., 14., 10.,
        9.,  9.,  6.,  7.,  9.,  9., 13., 15.,  9., 10.,  9.,  5., 10.,
       11., 10.,  9., 10., 13., 13., 13., 10., 13., 10., 12.,  9., 10.,
       12.,  9.,  9., 13., 12., 14.,  9., 11., 10., 10.,  9., 10., 10.,
       11., 10.,  9., 10.,  9.,  7., 10., 10.,  9., 13.,  9.,  9.,  9.,
       13., 10.,  9., 13.,  2.,  9., 14.,  9., 14., 10., 12., 14.,  7.,
       11.,  9.,  9., 10., 13., 13.,  9.,  9.,  9.,  9., 13., 10

In [ ]:
high = edu[edu>10]
low = edu[edu<=10]
print(high)
print(low)

[13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13. 13. 16. 13. 13. 13. 11. 13.
 13. 13. 13. 13. 11. 11. 13. 13. 14. 11. 13. 13. 13

In [55]:
income = data[:,7]
income

array([0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [56]:
avg_pay_low = np.mean(income[edu<=10])
avg_pay_low

0.13670133729569092

In [57]:
avg_pay_high = np.mean(income[edu>10])
avg_pay_high

0.42813455657492355